title: "BAKBAK's Blog"
email: bakbakminq@gmail.com
timezone: Asia/Seoul
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/smallhunter.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: ko-KR
lang: ko
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Minkyu Park
    display_name: BakBak MinQ
    avatar: 'assets/images/sal.png'
    email: bakbakminq@gmail.com
    web: https://github.com/bakbakminq/bakbakminq.github.io
    twitter: https://twitter.com/wowthemesnet
    description: "Let's GOGO"
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/_0_minq_0_
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  linkedin: https://www.linkedin.com/in/%EB%AF%BC%EA%B7%9C-%EB%B0%95-2837a22b6/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-FRHQ3PTQGZ"
    anonymize_ip         : # true, false (default)